optimization: reusing AEAD Cipher instance
RustCrypto/ring-compat pull request #79
Opened 2022-03-10 17:36 UTC by zonyitoo

The current implementation will require a copy operation of key for every call of `encrypt_*` and `decrypt_*` functions.

2022-03-10 18:03 UTC, tarcieri requested changes
Thanks! One small issue but otherwise this looks good

2022-03-11 01:02 UTC, zonyitoo commented on src/aead.rs
> -        }
Done removed `zeroize`.

2022-03-11 01:03 UTC, tarcieri approved these changes

2022-03-11 01:03 UTC, merged

2022-03-11 01:07 UTC, zonyitoo commented
One more thing: `digest` should be upgraded to `^1.10`. I am working on it.

2022-03-11 01:09 UTC, tarcieri commented
@zonyitoo `digest` needs to be upgraded in conjunction with the elliptic curve crate dependencies, which currently use `digest` v0.9.

The next release of the elliptic curve crate dependencies will upgrade to `digest` v0.10.

If you bump them now, you'll need to bump them all to prerelease versions.

2022-03-11 01:10 UTC, zonyitoo commented
Ah, then I will stop right here. Will you consider making a new release with these changes? @tarcieri

2022-03-11 01:24 UTC, tarcieri commented
Sure

2022-03-11 02:00 UTC, zonyitoo commented
Ah.. May I ask when will you publish it to crates.io?

2022-03-11 02:02 UTC, tarcieri commented
Currently working on some other things, but in the next day or so

2022-03-12 09:25 UTC, zonyitoo commented
Ah @tarcieri , sorry to disturb, would you make a release to crates.io today or tomorrow?

2022-03-12 19:02 UTC, tarcieri commented
#81